# -*- coding: utf-8 -*-
"""24083010072_Siti Rania Azaria_Tugas 01 Analisis Numerik (A)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUM0mfLr-rKhYC8edZZSTCmYxV-bF7s3
"""

# Nama: Siti Rania Azaria
# NPM: 24083010072

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import skewnorm

# Range harga jual (Rp)
x = np.linspace(3000, 10000, 500)

# Parameter distribusi
a = 6
loc = 3.5 * 1000     # Pergeseran kurva (lokasi)
scale = 1.5 * 1000   # Lebar sebaran (skala)

# Distribusi probabilitas dengan skew normal (condong ke kanan)
y = skewnorm.pdf(x, a=a, loc=loc, scale=scale) * 1000

# Menambah noise agar data lebih realistis
np.random.seed(10072) # Mengganti seed random dengan NPM
y = y + np.random.normal(0, 0.005, size=x.shape)  # Menambah noise Gaussian
y = y * 1000

# Data produksi
produksi_y = np.linspace(0, 1000, len(x))  # Jumlah produksi (unit)
produksi_z = np.linspace(3000, 2000, len(x)) + np.random.normal(0, 0.1, size=x.shape) * 100
# Biaya per unit menurun secara linear dari 3000 -> 2000 saat produksi 0 -> 1000

# Plot hubungan penjualan dan produksi
plt.figure(figsize=(8,5))
plt.plot(x, y, color="navy", label='Penjualan', linewidth=2)
plt.plot(produksi_z, produksi_y, color="red", label='Produksi', linewidth=2)
plt.title("Toko Roti Maknyus")
plt.xlabel("x (harga / biaya per unit)")
plt.ylabel("y (jumlah barang dibuat/laku)")
plt.grid(True)
plt.legend()
plt.show()

# TUGAS:
# Hitung volume produksi yang menghasilkan keuntungan maksimum (pendapatan dari penjualan dikurangi biaya produksi)

# Pendapatan = harga jual * jumlah terjual
pendapatan = x * y

# Biaya produksi = biaya per unit * jumlah produksi
biaya_produksi = produksi_z * produksi_y

# Keuntungan = pendapatan - biaya produksi
profit = pendapatan - biaya_produksi

# Cari volume produksi optimal (keuntungan maksimum)
indeks_optimal = np.argmax(profit)
volume_optimal = produksi_y[indeks_optimal]
harga_optimal = x[indeks_optimal]
profit_optimal = profit[indeks_optimal]

print("Volume produksi optimal :", volume_optimal)
print("Harga optimal           :", harga_optimal)
print("Keuntungan maksimum     :", profit_optimal)

# Plot keuntungan terhadap volume produksi
plt.figure(figsize=(8,5))
plt.plot(produksi_y, profit, color="green", linewidth=2, label="Keuntungan")
plt.scatter(volume_optimal, profit_max, color="red", s=80, label="Optimum", zorder=5)
plt.title("Keuntungan terhadap Volume Produksi")
plt.xlabel("Volume Produksi (jumlah barang)")
plt.ylabel("Keuntungan")
plt.grid(True)
plt.legend()
plt.show()

